// Generated by gencpp from file shared_files/Encoder.msg
// DO NOT EDIT!


#ifndef SHARED_FILES_MESSAGE_ENCODER_H
#define SHARED_FILES_MESSAGE_ENCODER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace shared_files
{
template <class ContainerAllocator>
struct Encoder_
{
  typedef Encoder_<ContainerAllocator> Type;

  Encoder_()
    : R(0)
    , L(0)  {
    }
  Encoder_(const ContainerAllocator& _alloc)
    : R(0)
    , L(0)  {
  (void)_alloc;
    }



   typedef uint8_t _R_type;
  _R_type R;

   typedef uint8_t _L_type;
  _L_type L;




  typedef boost::shared_ptr< ::shared_files::Encoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::shared_files::Encoder_<ContainerAllocator> const> ConstPtr;

}; // struct Encoder_

typedef ::shared_files::Encoder_<std::allocator<void> > Encoder;

typedef boost::shared_ptr< ::shared_files::Encoder > EncoderPtr;
typedef boost::shared_ptr< ::shared_files::Encoder const> EncoderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::shared_files::Encoder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::shared_files::Encoder_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace shared_files

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'shared_files': ['/home/odroid/AggreGator3.1/src/shared_files/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::shared_files::Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::shared_files::Encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shared_files::Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shared_files::Encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shared_files::Encoder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shared_files::Encoder_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::shared_files::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9e485da10e021927ec7b0ce8e3d5f8ab";
  }

  static const char* value(const ::shared_files::Encoder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9e485da10e021927ULL;
  static const uint64_t static_value2 = 0xec7b0ce8e3d5f8abULL;
};

template<class ContainerAllocator>
struct DataType< ::shared_files::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "shared_files/Encoder";
  }

  static const char* value(const ::shared_files::Encoder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::shared_files::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#values represend Right ENcoder Left Encoder\n\
uint8 R\n\
uint8 L\n\
\n\
";
  }

  static const char* value(const ::shared_files::Encoder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::shared_files::Encoder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.R);
      stream.next(m.L);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Encoder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::shared_files::Encoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::shared_files::Encoder_<ContainerAllocator>& v)
  {
    s << indent << "R: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.R);
    s << indent << "L: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.L);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SHARED_FILES_MESSAGE_ENCODER_H
